### ISSUE TITLE
Git submodule

### ISSUE THREAD

**Issue by reyhansofian** [codeigniter-id/user-guide#1]
Gimana klo nanti repo ini dijadikan submodule?

**Comment by SunDi3yansyah** [comment]
https://github.com/codeigniter-id/codeigniter-id.github.io/commit/13a54df0a0341be8e36126b5ec2ddbe7ed68d38a

**Comment by SunDi3yansyah** [comment]
Itu artinya jika repo ini di buat submodule gk bisa dibuka di gh page dong? kan rencananya biar bisa di akses oleh user :smile: kalau emang bisa gimana caranya?
https://help.github.com/articles/page-build-failed-invalid-submodule/

---

Untuk saat ini sih aku ngasih liat demo user guide bahasa indonesia baru disini http://php-codeigniterid.rhcloud.com/v3/

**Comment by reyhansofian** [comment]
https://help.github.com/articles/using-submodules-with-pages/

Disitu di tulis
`If your repository contains submodules, they will automatically be pulled in when the Page is built.`

**Comment by SunDi3yansyah** [comment]
Iya tadi sudah saya edit tidak pakai SSH harus pake protokol HTTPS, tadi saya buka kok 404 eh ternyata karus di tambah `v3` soalnya gk liat dir tadi

http://codeigniter-id.github.io/user_guide/v3/

**Comment by reyhansofian** [comment]
:D ok, sudah fix ya. Di close aja klo gt
